#!/usr/bin/env python3
"""pass-03d-pass-generator entrypoint (deterministic).

The compiler grows itself. It reads the self-improvement backlog in
``agents/self_improvement.md`` (a "ledger" special dependency — editing the
ledger invalidates this pass), selects the top unresolved ``- [ ]`` proposal
under the ``## Backlog`` heading, and scaffolds a new pass directory under
``compiler/passes/``:

    pass-NN-<slug>/
        pass.yaml     declarative metadata (id, consumes, produces, ...)
        run.py        deterministic stub that, when run, writes a <id>-ir
                      artifact capturing the proposed capability (so the
                      generated pass is inspectable + runnable immediately)
        prompt.md     the natural-language spec for the capability, consumed
                      by the generated pass when it later runs with --local

The next compiler run discovers the generated pass and executes it, closing
the loop: the backlog proposes a capability, the generator materialises it,
and the generated pass contributes to the knowledge graph / research output.

This makes the self-improvement ledger a *living* work queue: resolving an item
is done by the compiler, not by a human editing code.

Invocation: python run.py <build_dir>
"""

from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timezone

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(_HERE))
for _p in (_REPO, os.path.join(_REPO, "compiler")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from core import (  # noqa: E402
    DiagnosticEmitter,
    write_artifact,
    write_evaluation,
    evaluate_artifact,
)
from core.artifacts import ArtifactStore  # noqa: E402

PRODUCES = "pass-generator-ir"
CONSUMES = ["ledger"]

BACKLOG_HEADING = "## Backlog"

# Templates for the generated pass. Use {field} placeholders; the run.py
# template is a normal Python triple-quoted string (no nested quoting needed).
_PASS_YAML = """\
id: {pass_id}
name: {title}
produces: {produces}
consumes: [knowledge-extraction-ir, gap-analysis-ir]
entrypoint: run.py
deterministic: true
model_required: false
generated_by: pass-03d-pass-generator
description: >
  Auto-generated from the self-improvement backlog. {title}
"""

_PASS_RUN = '''\
#!/usr/bin/env python3
"""Auto-generated pass: {pass_id}.

Generated by pass-03d-pass-generator from the self-improvement backlog item:
  "{title}"

This deterministic stub reads the relevant upstream artifacts and writes
`{produces}` carrying the proposed capability's spec, so the pass is
inspectable and runnable immediately. Replace the body with the real
implementation (or set model_required: true and fill prompt.md for a
model-driven capability).
"""

from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(_HERE))
for _p in (_REPO, os.path.join(_REPO, "compiler")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from core import (
    DiagnosticEmitter, write_artifact, write_evaluation, evaluate_artifact,
)
from core.artifacts import ArtifactStore

PRODUCES = "{produces}"
CONSUMES = ["knowledge-extraction-ir", "gap-analysis-ir"]


def main() -> int:
    build_dir = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    store = ArtifactStore(build_dir)
    spec = ""
    prompt_path = os.path.join(_HERE, "prompt.md")
    if os.path.isfile(prompt_path):
        spec = open(prompt_path, encoding="utf-8").read()
    ir = {{
        "schema_version": "1.0",
        "generated": True,
        "prompt_spec": spec,
        "note": "auto-generated stub; implement the real capability",
    }}
    emitter = DiagnosticEmitter(PRODUCES, build_dir)
    emitter.info("GENERATED_STUB", "auto-generated pass ran")
    emitter.write()
    meta = write_artifact(
        build_dir, PRODUCES, ir, pass_id="{pass_id}",
        source_artifacts=CONSUMES, schema_id=PRODUCES,
        pass_dir=_HERE,
    )
    ev = evaluate_artifact(
        PRODUCES, ir, meta,
        hints={{"coverage": 1.0, "traceability": 1.0, "reproducibility": 1.0,
                "consistency": 1.0, "hallucination": 0.0}},
    )
    write_evaluation(build_dir, PRODUCES, ev)
    print(f"info: {{PRODUCES}} written (auto-generated stub)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

_PASS_PROMPT = """\
# Capability spec: {title}

Proposed by the self-improvement ledger (auto-selected by
pass-03d-pass-generator).

## Intent
{title}

## Notes
{notes}

## Acceptance
When this pass runs it should read the relevant existing artifacts, produce
`{produces}`, and (if model_required) emit a concrete artifact that advances
the research loop.
"""


def _slug(s: str) -> str:
    # Strip markdown/quoting noise, collapse to hyphenated lowercase, cap at a
    # word boundary near 24 chars so generated pass dirs stay readable.
    s = s.lower()
    s = re.sub(r"[`*\"]", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    if len(s) <= 24:
        return s or "task"
    cut = s[:24]
    if "-" in cut:
        cut = cut[: cut.rfind("-")]
    return cut or "task"


def parse_backlog(ledger_text: str) -> list[dict]:
    """Return unresolved backlog items as {title, body, checked}."""
    lines = ledger_text.splitlines()
    in_backlog = False
    items: list[dict] = []
    current: dict | None = None
    for ln in lines:
        if ln.startswith("## "):
            in_backlog = ln.strip().startswith(BACKLOG_HEADING)
            current = None
            continue
        if not in_backlog:
            continue
        m = re.match(r"^\s*-\s*\[( |x|X)\]\s*(.*)$", ln)
        if m:
            checked = m.group(1).lower() == "x"
            title = m.group(2).strip()
            current = {"title": title, "checked": checked, "body": []}
            items.append(current)
        elif current is not None and ln.strip().startswith("-"):
            current["body"].append(ln.strip())
    return [i for i in items if not i["checked"]]


def next_pass_id(passes_dir: str) -> str:
    """Find the next free pass-NN id by scanning existing directories."""
    highest = 0
    for name in os.listdir(passes_dir):
        m = re.match(r"^pass-(\d+)-", name)
        if m:
            highest = max(highest, int(m.group(1)))
    return f"pass-{highest + 1:02d}"


def scaffold(item: dict, passes_dir: str) -> dict:
    """Write a runnable pass directory for the backlog item. Returns metadata."""
    base_id = next_pass_id(passes_dir)
    slug = _slug(item["title"])
    pass_id = f"{base_id}-{slug}"
    pass_dir = os.path.join(passes_dir, pass_id)
    os.makedirs(pass_dir, exist_ok=True)
    produces = f"{pass_id}-ir"
    notes = "\n".join(item["body"] or ["(no additional notes)"])

    yaml_text = _PASS_YAML.format(pass_id=pass_id, title=item["title"],
                                  produces=produces)
    run_text = _PASS_RUN.format(pass_id=pass_id, title=item["title"],
                                produces=produces)
    prompt = _PASS_PROMPT.format(title=item["title"], notes=notes,
                                 produces=produces)

    with open(os.path.join(pass_dir, "pass.yaml"), "w", encoding="utf-8") as fh:
        fh.write(yaml_text)
    with open(os.path.join(pass_dir, "run.py"), "w", encoding="utf-8") as fh:
        fh.write(run_text)
    with open(os.path.join(pass_dir, "prompt.md"), "w", encoding="utf-8") as fh:
        fh.write(prompt)
    return {
        "pass_id": pass_id,
        "produces": produces,
        "title": item["title"],
        "path": os.path.relpath(pass_dir, _REPO),
        "prompt_chars": len(prompt),
    }


def main() -> int:
    build_dir = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    store = ArtifactStore(build_dir)
    repo = os.path.dirname(build_dir)
    ledger_path = os.path.join(repo, "agents", "self_improvement.md")
    if not os.path.isfile(ledger_path):
        print("error: ledger missing at", ledger_path, file=sys.stderr)
        return 1
    ledger = open(ledger_path, encoding="utf-8").read()
    backlog = parse_backlog(ledger)

    emitter = DiagnosticEmitter(PRODUCES, build_dir)
    if not backlog:
        emitter.info("NO_BACKLOG", "self-improvement backlog is empty")
        emitter.write()
        ir = {"schema_version": "1.0", "generated_pass": None,
              "backlog_remaining": 0, "note": "backlog empty"}
        meta = write_artifact(build_dir, PRODUCES, ir,
                              pass_id="pass-03d-pass-generator",
                              source_artifacts=CONSUMES, schema_id=PRODUCES,
                              pass_dir=os.path.dirname(os.path.abspath(__file__)))
        ev = evaluate_artifact(PRODUCES, ir, meta,
            hints={"coverage": 1.0, "traceability": 1.0, "reproducibility": 1.0,
                   "consistency": 1.0, "hallucination": 0.0})
        write_evaluation(build_dir, PRODUCES, ev)
        print("info: backlog empty; no pass generated")
        return 0

    top = backlog[0]
    passes_dir = os.path.join(_REPO, "passes")
    gen = scaffold(top, passes_dir)

    ir = {
        "schema_version": "1.0",
        "generated_pass": gen,
        "backlog_remaining": len(backlog) - 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "note": "compiler extended itself from the self-improvement backlog",
    }
    emitter.info("PASS_GENERATED",
                 f"scaffolded {gen['pass_id']} from backlog: {gen['title']}")
    emitter.write()
    meta = write_artifact(build_dir, PRODUCES, ir,
                          pass_id="pass-03d-pass-generator",
                          source_artifacts=CONSUMES, schema_id=PRODUCES,
                          pass_dir=os.path.dirname(os.path.abspath(__file__)))
    ev = evaluate_artifact(PRODUCES, ir, meta,
        hints={"coverage": 1.0, "traceability": 1.0, "reproducibility": 1.0,
               "consistency": 1.0, "hallucination": 0.0})
    write_evaluation(build_dir, PRODUCES, ev)

    print(f"info: generated pass {gen['pass_id']} -> {gen['path']} "
          f"(backlog remaining: {len(backlog) - 1})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
